version: '3.9'

services:

  postgres:
    image: postgres:latest
    container_name: ${DB_HOST}
    ports:
     - 5432:${DB_PORT}
    environment:
     - POSTGRES_USER=${DB_USER}
     - POSTGRES_PASSWORD=${DB_PASS}
     - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 1
    networks:
      - appnet

  app:
    build:
      dockerfile: ./app.Dockerfile
    container_name: ${SERVER_HOST}
    ports:
     - 8080:${SERVER_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - appnet

networks:
 appnet:
  name: appnet
  driver: bridge